### ISSUE TITLE
Use CDATA for containing newlines

### ISSUE THREAD

**Issue by Zverik** [iandees/planet-notes-dump#4]
Whitespace in XML is just a whitespace: newlines do not differ from spaces, for example. To preserve line feeds in comments, please enclose comments in `<![CDATA[.....]]>`.

https://github.com/iandees/planet-notes-dump/blob/master/dump.py#L57

**Comment by joto** [comment]
I am not happy about this change. Just bloats the file for no reason really. How we interpret the whitespace in XML files is up to us, we can certainly say the newlines are important. Or are there parsers that mangle the data otherwise? @Zverik: Can you give some more reasons where this would be problematic?

At the very least, the empty CDATA sections on empty comments should be removed.

**Comment by joto** [comment]
I just noticed there is a check for an empty body in the code (https://github.com/iandees/planet-notes-dump/blob/master/dump.py#L56). In the dump there are about 20,000 comments with empty body, which match this test, but about 60,000 which don't. I guess this is the difference between SQL NULL and '' (empty string with length 0).

Maybe this should be fixed in the database, so that there is only one case here and not two. Somebody would have to check the code adding notes to the database. Maybe add a NOT NULL constraint to the body?

**Comment by Zverik** [comment]
I searched the web for proper newline representation in XML — obviously `<br/>` won't do — and found [this stackoverflow page](http://stackoverflow.com/questions/10917555/adding-a-new-line-break-tag-in-xml). It says special characters (like \r\n) would only be preserved in CDATA sections. Of course, I'm not against omitting the CDATA for single-line comments.

As for empty comments, please make a separate issue.

**Comment by joto** [comment]
Okay, there is some confusion here and the stackoverflow page you mention makes it worse, because it mixes the issue with the issue how to do `<br/>` properly which is a HTML tag and not an XML issue. In XML a newline is simply a newline character in the data. I can't find anything that says, newlines are handled differently in CDATA sections than in normal character data in XML. The [standard](http://www.w3.org/TR/REC-xml/) says: "CDATA sections may occur anywhere character data may occur; they are used to escape blocks of text containing characters which would otherwise be recognized as markup." Nothing about newlines in that section. (Carriage returns are [always handled specially](http://www.w3.org/TR/REC-xml/#sec-line-ends), but that happens inside CDATA and outside.)

So any parser should produce the same characters when parsing the following:

```
<foo>a
b
c</foo>
```

and

```
<foo><![CDATA[a
b
c]]></foof>
```

Note that with HTML it is a bit different, because HTML will normally treat newlines as spaces, to force a newline you can use `<br/>` inside paragraphs for instance, but you can also wrap text in `<pre>...</pre>` and the newlines will be kept. But all of that is a feature of how HTML interprets the data, not of the XML that might be used when using XHTML.

**Comment by iandees** [comment]
Thanks @joto, was just about to write what you wrote.

An XML parser can handle whitespace just fine:

``` python
>>> from lxml import etree
>>> el = etree.fromstring('<beep>foo\nbar</beep>')
>>> el.text
'foo\nbar'
```

**Comment by Zverik** [comment]
Okay, you are right.
